# Netlify デプロイ設定ファイル

[build]
  # ビルドコマンド
  command = "npm run build:prod"
  
  # 公開ディレクトリ
  publish = "dist"
  
  # 環境変数
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Netlifyビルド時の環境変数
  VITE_APP_ENV = "production"

# SPAのためのリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ヘッダー設定
[[headers]]
  for = "/*"
  
  [headers.values]
    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # キャッシュ制御（HTML）
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  
  [headers.values]
    # アセットの長期キャッシュ
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  
  [headers.values]
    # JavaScriptファイルのキャッシュ
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  
  [headers.values]
    # CSSファイルのキャッシュ
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/data/*"
  
  [headers.values]
    # JSONデータのキャッシュ（1時間）
    Cache-Control = "public, max-age=3600"

# プラグイン設定
[[plugins]]
  # ビルド時間の最適化
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    # Lighthouseの設定
    output_path = "reports/lighthouse.html"
    
    [[plugins.inputs.audits]]
      url = "/"
      
      [plugins.inputs.audits.thresholds]
        performance = 0.9
        accessibility = 0.9
        best-practices = 0.9
        seo = 0.9